const response = {
    "modal": [{
            "index": 17,
            "token": "can",
            "end": 106,
            "start": 103
        }, {
            "index": 69,
            "token": "would",
            "end": 361,
            "start": 356
        }, {
            "index": 75,
            "token": "can",
            "end": 386,
            "start": 383
        }, {
            "index": 96,
            "token": "can",
            "end": 485,
            "start": 482
        }, {
            "index": 104,
            "token": "won’t",
            "end": 532,
            "start": 527
        }, {
            "index": 122,
            "token": "might",
            "end": 641,
            "start": 636
        }, {
            "index": 127,
            "token": "will",
            "end": 669,
            "start": 665
        }, {
            "index": 141,
            "token": "will",
            "end": 734,
            "start": 730
        }],
    "adverbs": [{
            "index": 9,
            "token": "continuously",
            "end": 60,
            "start": 48
        }, {
            "index": 19,
            "token": "better",
            "end": 116,
            "start": 110
        }, {
            "index": 33,
            "token": "enough",
            "end": 186,
            "start": 180
        }, {
            "index": 42,
            "token": "always",
            "end": 229,
            "start": 223
        }, {
            "index": 51,
            "token": "only",
            "end": 281,
            "start": 277
        }, {
            "index": 52,
            "token": "when",
            "end": 286,
            "start": 282
        }, {
            "index": 57,
            "token": "Only",
            "end": 308,
            "start": 304
        }, {
            "index": 58,
            "token": "when",
            "end": 313,
            "start": 309
        }, {
            "index": 63,
            "token": "Only",
            "end": 336,
            "start": 332
        }, {
            "index": 64,
            "token": "when",
            "end": 341,
            "start": 337
        }, {
            "index": 76,
            "token": "clearly",
            "end": 394,
            "start": 387
        }, {
            "index": 78,
            "token": "now",
            "end": 402,
            "start": 399
        }, {
            "index": 98,
            "token": "truly",
            "end": 497,
            "start": 492
        }, {
            "index": 136,
            "token": "Also",
            "end": 708,
            "start": 704
        }, {
            "index": 146,
            "token": "else",
            "end": 757,
            "start": 753
        }, {
            "index": 157,
            "token": "rather",
            "end": 794,
            "start": 788
        }],
    "weakverbs": [{
        "index": 12,
        "token": "work",
        "end": 80,
        "start": 76
    }, {
        "index": 18,
        "token": "do",
        "end": 109,
        "start": 107
    }, {
        "index": 30,
        "token": "work",
        "end": 171,
        "start": 167
    }, {
        "index": 43,
        "token": "had",
        "end": 233,
        "start": 230
    }, {
        "index": 46,
        "token": "need",
        "end": 253,
        "start": 249
    }, {
        "index": 50,
        "token": "work",
        "end": 276,
        "start": 272
    }, {
        "index": 54,
        "token": "felt",
        "end": 294,
        "start": 290
    }, {
        "index": 60,
        "token": "felt",
        "end": 321,
        "start": 317
    }, {
        "index": 77,
        "token": "see",
        "end": 398,
        "start": 395
    }, {
        "index": 81,
        "token": "need",
        "end": 417,
        "start": 413
    }],
"nomilization": [{
        "index": 83,
        "token": "perfection",
        "end": 432,
        "start": 422
    }, {
        "index": 86,
        "token": "illusion",
        "end": 447,
        "start": 439
    }, {
        "index": 112,
        "token": "perfection",
        "end": 584,
        "start": 574
    }, {
        "index": 125,
        "token": "ambition",
        "end": 660,
        "start": 652
    }, {
        "index": 133,
        "token": "rejection",
        "end": 701,
        "start": 692
    }]
};
    export default response;